# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Creative portfolio"
license = "MIT"
licenselink = "https://github.com/kishaningithub/hugo-creative-portfolio-theme/blob/master/LICENSE"
description = "Open Source Medical Supplies Peru"
homepage = "https://github.com/healthinnovation/osms-peru.github.io"
tags = ["creative", "portfolio", "projects", "minimal", "responsive"]
features = ["disqus", "bootstrap", "responsive", "google analytics"]
min_version = 0.20

[author]
  name = "Laboratorio de Innovación en Salud"
  homepage = "https://github.com/healthinnovation"

# If porting an existing theme
[original]
  name = "bootstrapious"
  homepage = "https://bootstrapious.com/p/creative-portfolio"
